### getAll
GET http://localhost:4000/api/agendas HTTP/1.1

### getById
GET http://localhost:4000/api/agendas/1 HTTP/1.1

### getInfo
GET http://localhost:4000/api/agendas/info/55 HTTP/1.1

### getTopicsFrom
GET http://localhost:4000/api/agendas/topics/1?year=2038 HTTP/1.1

### getTopics
GET http://localhost:4000/api/agendas/1/topics HTTP/1.1

### create
POST http://localhost:4000/api/agendas HTTP/1.1
Content-Type: application/json

# {
#   "year":"2025-11-21T19:15:05.706Z",
#   "idArea":1
# }

{
    "id": "",
    "year": 2003,
    "idTypeOfMeeting": 1,
    "topics":[
      {
        "id":-1,
        "name":"tema de enero",
        "monthNumber":0
      },
      {
        "id":-2,
        "name":"tema de enero 2",
        "monthNumber":0
      },
      {
        "id":-3,
        "name":"tema de enero 3",
        "monthNumber":0
      },
      {
        "id":-4,
        "name":"tema de junio",
        "monthNumber":5
      }
    ]
}

### update
PATCH  http://localhost:4000/api/agendas/55 HTTP/1.1
Content-Type: application/json

{
    "id": 55,
    "year": "2011-01-01T05:00:00.000Z",
    "idTypeOfMeeting": 1,
    "topics": [
      {
        "id": 126,
        "name": "el de enero",
        "month": "2011-01-01T05:00:00.000Z",
        "monthNumber": 0
      },
      {
        "id": 127,
        "name": "el de enero2",
        "month": "2011-01-01T05:00:00.000Z",
        "monthNumber": 0
      },
      {
        "id": 128,
        "name": "el de ahora mismo",
        "month": "2011-04-01T04:00:00.000Z",
        "monthNumber": 3
      },
      {
        "id": -1,
        "name": "el de marzo",
        "month": "2011-03-01T05:00:00.000Z",
        "monthNumber": 2
      },
      {
        "id": -2,
        "name": "el de diciembre",
        "month": "2011-12-01T04:00:00.000Z",
        "monthNumber": 11
      }
    ]
  }
