### getAll
GET http://localhost:4000/api/organizations HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmYzEzMWYwLTIzZjUtMTFmMC1iZDI0LWNiOTMzOWVlNWExZSIsInVzZXJuYW1lIjoiaGdhcmNpYSIsInJvbGUiOiJMw41ERVIiLCJpYXQiOjE3NDYwNzAxOTMsImV4cCI6MTc0NjA3MDI1M30.OvTOZCy4zYc0o8BCTO_VJ56be1oTyR1x1a8ope-C3aM

### getById
GET http://localhost:4000/api/organizations/1 HTTP/1.1

### getAllFrom
GET http://localhost:4000/api/organizations/leader/cfc131f0-23f5-11f0-bd24-cb9339ee5a1e HTTP/1.1

### update
PATCH http://localhost:4000/api/organizations/6 HTTP/1.1
Content-Type: application/json

{
  "id": 6,
  "name": "Seis. Siete",
  "state": true,
  "idLeader": "6b4f78c0-efee-11ef-a14b-dbf1a2c78c20"
}

### create
POST http://localhost:4000/api/organizations HTTP/1.1
Content-Type: application/json

{
  "name": "Ocho",
  "idLeader":"9ddb61f0-efee-11ef-a14b-dbf1a2c78c20"
}
